# application name
APPLICATION := tcpecho

# Modules needed by the application
MODULES := 	base \
            lpc_chip_175x_6x \
				lpc_board_nxp_lpcxpresso_1769 \
				freertos \
				lwip

# source files folder
SRC_FOLDERS += examples/tcpecho/src

# header files folder
INC_FOLDERS += examples/tcpecho/inc

# source files
C_FILES += $(wildcard examples/tcpecho/src/*.c)
ASM_FILES += $(wildcard examples/tcpecho/src/*.S)
