# application name
APPLICATION := usb_cdc

# Modules needed by the application
MODULES := 	base \
            lpc_chip_175x_6x \
				lpc_board_nxp_lpcxpresso_1769 \
				freertos

# source files folder
SRC_FOLDERS += examples/usb_cdc/src

# header files folder
INC_FOLDERS += examples/usb_cdc/inc

# source files
C_FILES += $(wildcard examples/usb_cdc/src/*.c)
ASM_FILES += $(wildcard examples/usb_cdc/src/*.S)
