# application name
APPLICATION := blink

# Modules needed by the application
MODULES := 	lpc_chip_175x_6x \
				lpc_board_nxp_lpcxpresso_1769

# source files folder
SRC_FOLDERS += examples/$(APPLICATION)/src

# header files folder
INC_FOLDERS += examples/$(APPLICATION)/inc

# source files
C_FILES += $(wildcard examples/$(APPLICATION)/src/*.c)
ASM_FILES += $(wildcard examples/$(APPLICATION)/src/*.S)
