# application name
APPLICATION := freertos_blink

# Modules needed by the application
MODULES := 	base \
            lpc_chip_175x_6x \
				lpc_board_nxp_lpcxpresso_1769 \
				freertos

# source files folder
SRC_FOLDERS += examples/freertos_blink/src

# header files folder
INC_FOLDERS += examples/freertos_blink/inc

# source files
C_FILES += $(wildcard examples/freertos_blink/src/*.c)
ASM_FILES += $(wildcard examples/freertos_blink/src/*.S)
