C_FILES += $(wildcard modules/lwip/src/api/*.c)
C_FILES += $(wildcard modules/lwip/src/arch/*.c)
C_FILES += $(wildcard modules/lwip/src/core/*.c)
C_FILES += $(wildcard modules/lwip/src/core/ipv4/*.c)
C_FILES += $(wildcard modules/lwip/src/netif/*.c)

INC_FOLDERS += modules/lwip/inc modules/lwip/inc/ipv4

SRC_FOLDERS += modules/lwip/src/api 		\
				modules/lwip/src/arch 		\
				modules/lwip/src/core 		\
				modules/lwip/src/core/ipv4 \
				modules/lwip/src/netif
