C_FILES += $(wildcard modules/lpc_chip_175x_6x/src/*.c)

INC_FOLDERS += modules/lpc_chip_175x_6x/inc \
					modules/lpc_chip_175x_6x/inc/usbd

SRC_FOLDERS += modules/lpc_chip_175x_6x/src

LIBS_FOLDERS += modules/lpc_chip_175x_6x/libs

LIBS += usbd_175x_6x_lib
